---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ppbz7941/public_html/siparoki.ppbgmadrossoe.com/
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R bootstrap $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R lang $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp artisan $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/storage/framework/sessions
    - /bin/mkdir -p $DEPLOYPATH/storage/framework/views
    - /bin/mkdir -p $DEPLOYPATH/storage/framework/cache/data
    - /bin/mkdir -p $DEPLOYPATH/storage/logs
    - /bin/mkdir -p $DEPLOYPATH/storage/app/public
    - /bin/mkdir -p $DEPLOYPATH/bootstrap/cache
    - /bin/chmod -R 775 $DEPLOYPATH/storage $DEPLOYPATH/bootstrap/cache

